### ISSUE TITLE
template tag doesn't work in tbody

### ISSUE THREAD

**Issue by hobbit125** [aurelia/html-template-element#3]
In IE, if you attempt to place a template tag directly within a tbody tag, it appears to be ignored.

Use case:  Want all grandchildren of a collection to be shown in rows:

```
<table>
  <tbody>
    <template repeat.for="grp in data.rowGroups">
      <tr repeat.for="row in grp.Rows">
          <td>Test</td>
      </tr>
    </template>
  </tbody>
</table>
```

**Comment by EisenbergEffect** [comment]
Doubtful we will be able to fix this, due to the way IE handles tables. We may be able to provide a comment-style workaround. Placing the repeat on the tr should be fine, but it's the presence of the template element inside the tbody that causes IE to strip it out before we can even read it.

**Comment by Ixonal** [comment]
Just wanted to poke here, as I'm starting to run into this now. I'm wanting to add two rows for every item in a list inside of a table. Ex:

``` html
<table>
  <tbody>
    <template repeat.for="row of rows">
       <tr></tr>
       <tr></tr>
    </template>
  </tbody>
</table>
```

I can't really think of an alternate way to do this properly... I could put the repeat on the tbody, but that's not really right. Has there been any progress on the comment-style workaround? I'm assuming it'd be like comment bindings in Knockout. I found them helpful in various other circumstances as well, so they might be a nice generic addition.

Edit: I suppose one option for me could be to create a custom attribute similar to repeat.for, but that only repeats the inner html content, and leaves the containing element as-is. Kind of like how Knockout's foreach binding works. That way, I could just put it directly on the tbody.

**Comment by gavinaiken** [comment]
Anyone know what the status of this issue is?

**Comment by EisenbergEffect** [comment]
It's not possible to make this work without native template support. It's literally impossible. However, we are considering some workarounds, such as potentially attributing elements with `template-start` and `template-end`. Perhaps like this:

``` html
<table>
  <tbody>
       <tr repeat.for="row of rows" template-start></tr>
       <tr template-end></tr>
  </tbody>
</table>
```

^^^Something like that. What do you think?

**Comment by Ixonal** [comment]
Feels kind of odd... Maybe just because it's new or something.

Is the alternate repeat attribute i was contemplating not workable? I kind of gave up on it because I got told not to use Aurellia :(

**Comment by hobbit125** [comment]
I think the workaround suggested is fine.  It's a corner case and there's no normal way to handle it.

**Comment by Ixonal** [comment]
True. 

Would those attributes have an effect on other binding constructs, or be limited to just repeats?

**Comment by Mordred** [comment]
Based on http://stackoverflow.com/questions/3076708/can-we-have-multiple-tbody-in-same-table I end up with this:

``` html
<table>
  <tbody repeat.for="row of rows">
       <tr>1. line</tr>
       <tr>2. line</tr>
  </tbody>
</table>
```

**Comment by EisenbergEffect** [comment]
@Ixonal The ideas is that the repeat-start, etc would affect all template controller attributes: repeat, if, with, etc. and any user defined behaviors as well.

**Comment by EisenbergEffect** [comment]
@Mordred Cool! I didn't know that was possible. Very nice.

**Comment by Ixonal** [comment]
@EisenbergEffect still feels a bit wonky to me, but if it works, it works.

@Mordred yeah, it's possible to do that, but the generated markup wouldn't really match the intent, and may cause issues with css frameworks. If those aren't relevant concerns, though, go for it :)

**Comment by EisenbergEffect** [comment]
@Ixonal Do you have any alternate ideas? We are open to suggestions.

**Comment by Ixonal** [comment]
@EisenbergEffect think i read the markup wrong the first time. Thought the repeat was on the table body. Having it on the row is a little better. Might let the attributes have an optional value to specify a sort of id to make it more obvious where a particular template starts and stops. My initial thought was that the repeat binding could be altered to give the option to only repeat its children, but you know better than me whether or not that's possible. Something like repeat.in="foo of bar" or repeat.for="foo in bar" to determine that the template should be composed of children only.

**Comment by EisenbergEffect** [comment]
I think I would favor the `template-start` and `template-end` a bit more because we could bake that into the compiler and then enable the same thing to work with no only the repeat but also, if with, etc. automatically.

**Comment by Ixonal** [comment]
Would that replace what the template tag does for those other cases, or would there just be two ways to have containerless control statements now?

**Comment by EisenbergEffect** [comment]
It would basically be an alternative to the template element and could handle all containerless control scenarios.

**Comment by Ixonal** [comment]
Sounds alright to me, then.

**Comment by gavinaiken** [comment]
Would be great to have a work-around that would work with all the other templating keywords also, so I like the `template-start` / `template-end` idea for that reason.

**Comment by smithaitufe** [comment]
I had issue working tables today. I realized it is using template inside the table tag that caused my rows from been rendered. I think the template-start and template-end is better. Does it mean when we want to use nested component built with TR, we will not longer need to use template?

**Comment by jdanyow** [comment]
@EisenbergEffect can this be transitioned to an enhancment for the template-start / template-end feature?

**Comment by HenryKeen** [comment]
Massive thanks for the template-start / template-end workarounds @EisenbergEffect, they work a treat!

I've run into a stumbling block though, have you got any idea how I could replicate a nested repeat like this?

```
<tr>
    <template repeat.for="item1 of items1">
        <template repeat.for="item2 of items2">
            <td></td>
        </template>
    </template>
</tr>
```

**Comment by nano2nd** [comment]
Was template-start / template-end workaround ever added?

**Comment by davismj** [comment]
I mean, I don't think we need it. Rob proposed this above:

```html
<table>
  <tbody>
       <tr repeat.for="row of rows" template-start>row 1</tr>
       <tr template-end>row 2</tr>
  </tbody>
</table>
```

You can achieve this with the following:

```html
<table>
  <tbody>
    <template repeat.for="row of rows" containerless>
       <tr>row 1</tr>
       <tr>row 2</tr>
    </template>
  </tbody>
</table>
```

**Comment by jdanyow** [comment]
@davismj I think the template-start/end workaround is for IE.

IE doesn't have true template element support so it mangles the markup when you try to use template within a table.

**Comment by nano2nd** [comment]
Thanks @davismj this works in Chrome, but my issue is specifically with tables in IE11 where my bindings are breaking down even with "containerless". I have yet to get code in this form to work in IE11...

```
<table>
  <tbody>
    <template repeat.for="row of rows" containerless>
      <tr if.bind="bool_expr">${row.SomeVal}</tr>
    </template>
  </tbody>
</table>
```

**Comment by nano2nd** [comment]
oops we posted at the same time..is there no known workaround besides the repeating `<tbody>` implementation?

**Comment by sorenhoyer** [comment]
Not that I know of, but it would be very useful indeed - I often have the need to nest templates within tables, and most of our clients unfortunately require us to support ie. Looks like the Angular guys fixed this a while ago: https://github.com/angular/angular/issues/4830 - hopefully we'll also get it soon. One of the very very few things I miss with Aurelia.

**Comment by lancegiles** [comment]
I've just had a developer mention this issue to me for IE and the only work around he found is putting the template on the tbody (which I don't like since it messes up some of our css attributes when highlighting odd/even rows).  But we have to do what we have to do.  

Was the template-start / template-end ever designed?  I'd like to see if that resolves the issue.

**Comment by timfish** [comment]
I can't have multiple `<tbody>` as I wanted to set max-height on it and have it scroll all the rows. I ended up having to change to flex layout rather than table!

**Comment by jamesond** [comment]
Any one come up with a work around on this? Besides repeating tbody, seems pretty hacky.

**Comment by gavinaiken** [comment]
Repeating `tbody` or using flexbox were the only work arounds we came up with in our project.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating #565](https://github.com/aurelia/templating/issues/565) via [**ZenHub**](https://www.zenhub.com/)
